"""Score detections against farm_ground_truth.json.

This is the piece that turns verdicts into an FP/FN number. It is written to
be tolerant of the ground-truth file's exact shape, because that file is
generated by the world builder and its schema is not fixed: it walks the JSON
looking for a list of plant records, then looks for a health-ish field on
them. `--inspect` prints what it found so a mismatch is a one-flag fix rather
than an edit to this file.

## The unit of scoring

A detection judges a *frame*, and a frame contains several plants. So a
per-plant confusion matrix is not available from this data, and claiming one
would be dishonest. What is available:

  ROW mode (preferred, needs row_id on detections from the mission log)
      Ground truth per row: the row is anomalous if it holds at least
      `--row-threshold` diseased plants (default 1). Prediction per row: any
      frame from that row flagged STRESSED or DISEASED. TP/FP/FN/TN over rows.

  AGGREGATE mode (fallback, always available)
      Compares the predicted anomaly rate against the true diseased rate.
      This is a calibration check, NOT a confusion matrix -- it cannot tell a
      false positive from a false negative, and the report says so.

Report whichever mode actually ran, and name it. "Recall 0.83 over 6 rows" is
a defensible claim; "recall 0.83" with no unit is not.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

# Field names seen in generated ground-truth files, in priority order.
HEALTH_KEYS = ("health", "health_state", "healthState", "status", "state",
               "condition", "label", "class", "disease", "is_diseased",
               "diseased")
ROW_KEYS = ("row_id", "rowId", "row", "row_index", "rowIndex")
FIELD_KEYS = ("field_id", "fieldId", "field")
ID_KEYS = ("id", "plant_id", "plantId", "name", "model_name")

# Ground-truth values that mean "this plant is fine".
HEALTHY_VALUES = {"healthy", "health", "nominal", "ok", "good", "normal",
                  "none", "no_disease", "false", "0", "clean"}
# Everything else that is a recognised state means "not fine".
ANOMALY_VALUES = {"diseased", "disease", "infected", "unhealthy", "sick",
                  "stressed", "stress", "blight", "rust", "mildew", "wilt",
                  "chlorotic", "chlorosis", "necrotic", "true", "1", "dry",
                  "drought", "pest", "damaged"}


class GroundTruthError(RuntimeError):
    pass


@dataclass
class Plant:
    raw: dict
    ident: str | None
    row: str | None
    field: str | None
    diseased: bool


def _walk_lists(node: Any) -> Iterable[list]:
    """Yield every list-of-dicts found anywhere in the JSON."""
    if isinstance(node, list):
        if node and all(isinstance(x, dict) for x in node):
            yield node
        for x in node:
            yield from _walk_lists(x)
    elif isinstance(node, dict):
        for v in node.values():
            yield from _walk_lists(v)


def _first_key(d: dict, candidates: Iterable[str]) -> str | None:
    lowered = {k.lower(): k for k in d}
    for c in candidates:
        if c.lower() in lowered:
            return lowered[c.lower()]
    return None


def _is_diseased(value: Any) -> bool | None:
    """True/False if the value is recognised, None if it is not."""
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    if value is None:
        return None
    s = str(value).strip().lower()
    if s in HEALTHY_VALUES:
        return False
    if s in ANOMALY_VALUES:
        return True
    # Substring fallback: "leaf_blight_severe", "healthy_tomato".
    if any(a in s for a in ANOMALY_VALUES):
        return True
    if any(h in s for h in HEALTHY_VALUES):
        return False
    return None


def load_ground_truth(path: Path, health_key: str | None = None,
                      row_key: str | None = None) -> tuple[list[Plant], dict]:
    """Find the plant records in the ground-truth file and normalise them."""
    data = json.loads(Path(path).read_text())

    best: list[dict] | None = None
    best_key: str | None = None
    for candidate in _walk_lists(data):
        key = health_key or _first_key(candidate[0], HEALTH_KEYS)
        if key is None:
            continue
        recognised = sum(1 for rec in candidate
                         if _is_diseased(rec.get(key)) is not None)
        if best is None or len(candidate) > len(best):
            if recognised >= max(1, len(candidate) // 2):
                best, best_key = candidate, key

    if best is None:
        keys_seen = sorted({k for lst in _walk_lists(data) for k in lst[0]})
        raise GroundTruthError(
            "could not find plant records with a health field in "
            f"{path}.\nKeys available on the record lists found: {keys_seen}\n"
            "Pass --health-key to name the field explicitly.")

    rkey = row_key or _first_key(best[0], ROW_KEYS)
    fkey = _first_key(best[0], FIELD_KEYS)
    ikey = _first_key(best[0], ID_KEYS)

    plants: list[Plant] = []
    unknown = 0
    for rec in best:
        d = _is_diseased(rec.get(best_key))
        if d is None:
            unknown += 1
            continue
        plants.append(Plant(
            raw=rec,
            ident=str(rec[ikey]) if ikey and rec.get(ikey) is not None else None,
            row=str(rec[rkey]) if rkey and rec.get(rkey) is not None else None,
            field=str(rec[fkey]) if fkey and rec.get(fkey) is not None else None,
            diseased=d,
        ))

    meta = {
        "source": str(path),
        "health_key": best_key,
        "row_key": rkey,
        "field_key": fkey,
        "id_key": ikey,
        "records_found": len(best),
        "records_usable": len(plants),
        "records_unrecognised": unknown,
        "diseased": sum(1 for p in plants if p.diseased),
        "healthy": sum(1 for p in plants if not p.diseased),
        "distinct_values": sorted({str(r.get(best_key)) for r in best})[:12],
        "rows": sorted({p.row for p in plants if p.row}),
    }
    return plants, meta


def confusion(pairs: list[tuple[bool, bool]]) -> dict:
    """pairs of (truth_is_anomalous, prediction_is_anomalous)."""
    tp = sum(1 for t, p in pairs if t and p)
    fp = sum(1 for t, p in pairs if not t and p)
    fn = sum(1 for t, p in pairs if t and not p)
    tn = sum(1 for t, p in pairs if not t and not p)
    n = len(pairs)
    prec = tp / (tp + fp) if (tp + fp) else None
    rec = tp / (tp + fn) if (tp + fn) else None
    f1 = (2 * prec * rec / (prec + rec)) if (prec and rec) else None
    return {
        "n": n,
        "true_positives": tp,
        "false_positives": fp,
        "false_negatives": fn,
        "true_negatives": tn,
        "precision": round(prec, 3) if prec is not None else None,
        "recall": round(rec, 3) if rec is not None else None,
        "f1": round(f1, 3) if f1 is not None else None,
        "accuracy": round((tp + tn) / n, 3) if n else None,
        "false_positive_rate": (round(fp / (fp + tn), 3)
                                if (fp + tn) else None),
        "false_negative_rate": (round(fn / (fn + tp), 3)
                                if (fn + tp) else None),
    }


def score_by_row(detections, plants: list[Plant],
                 row_threshold: int = 1) -> dict | None:
    """Row-level confusion matrix. Returns None if rows are unavailable."""
    det_rows = {d.row_id for d in detections if d.row_id and d.judged}
    truth_rows = {p.row for p in plants if p.row}
    shared = det_rows & truth_rows
    if not shared:
        return None

    predicted: dict[str, bool] = {}
    for d in detections:
        if d.row_id in shared and d.judged:
            predicted[d.row_id] = predicted.get(d.row_id, False) or d.anomaly

    truth: dict[str, bool] = {}
    for row in shared:
        n_bad = sum(1 for p in plants if p.row == row and p.diseased)
        truth[row] = n_bad >= row_threshold

    pairs = [(truth[r], predicted[r]) for r in sorted(shared)]
    out = confusion(pairs)
    out["mode"] = "row"
    out["unit"] = "row"
    out["row_threshold"] = row_threshold
    out["rows_scored"] = sorted(shared)
    out["rows_in_truth_only"] = sorted(truth_rows - det_rows)
    out["rows_in_detections_only"] = sorted(det_rows - truth_rows)
    out["per_row"] = {r: {"truth_anomalous": truth[r],
                          "predicted_anomalous": predicted[r]}
                      for r in sorted(shared)}
    return out


def score_aggregate(detections, plants: list[Plant]) -> dict:
    """Calibration check when rows are unavailable. Not a confusion matrix."""
    judged = [d for d in detections if d.judged]
    pred_rate = (sum(1 for d in judged if d.anomaly) / len(judged)
                 if judged else None)
    true_rate = (sum(1 for p in plants if p.diseased) / len(plants)
                 if plants else None)
    return {
        "mode": "aggregate",
        "unit": "frame vs plant population",
        "frames_judged": len(judged),
        "frames_flagged": sum(1 for d in judged if d.anomaly),
        "predicted_anomaly_rate": (round(pred_rate, 3)
                                   if pred_rate is not None else None),
        "plants_in_truth": len(plants),
        "plants_diseased": sum(1 for p in plants if p.diseased),
        "true_diseased_rate": (round(true_rate, 3)
                               if true_rate is not None else None),
        "rate_error": (round(pred_rate - true_rate, 3)
                       if pred_rate is not None and true_rate is not None
                       else None),
        "caveat": (
            "Aggregate mode compares rates over different units (frames vs "
            "plants). It cannot separate false positives from false "
            "negatives, so no TP/FP/FN/TN is reported. Attach row_id to the "
            "detections (via the mission log) to get a real confusion matrix."
        ),
    }


def score(detections, plants: list[Plant], row_threshold: int = 1) -> dict:
    by_row = score_by_row(detections, plants, row_threshold)
    if by_row is not None:
        return by_row
    return score_aggregate(detections, plants)
